// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ShipDataProtoc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtocFiles {

  /// <summary>Holder for reflection information generated from ShipDataProtoc.proto</summary>
  public static partial class ShipDataProtocReflection {

    #region Descriptor
    /// <summary>File descriptor for ShipDataProtoc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShipDataProtocReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRTaGlwRGF0YVByb3RvYy5wcm90bxILUHJvdG9jRmlsZXMiXQoOU2hpcFNh",
            "dmVGaWxlX1ASGQoRU2hpcENoYXNzaXNfSW5kZXgYASABKAUSMAoMVHVycmV0",
            "TW91bnRzGAIgAygLMhouUHJvdG9jRmlsZXMuVHVycmV0TW91bnRfUCJVCg1U",
            "dXJyZXRNb3VudF9QEi4KClR1cnJldFR5cGUYASABKA4yGi5Qcm90b2NGaWxl",
            "cy5UdXJyZXRDbGFzc19QEhQKDFR1cnJldF9JbmRleBgCIAEoBSo1Cg1UdXJy",
            "ZXRDbGFzc19QEgcKA0FNUxAAEgcKA0FURxABEgcKA01TTBACEgkKBU9USEVS",
            "EANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtocFiles.TurretClass_P), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocFiles.ShipSaveFile_P), global::ProtocFiles.ShipSaveFile_P.Parser, new[]{ "ShipChassisIndex", "TurretMounts" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtocFiles.TurretMount_P), global::ProtocFiles.TurretMount_P.Parser, new[]{ "TurretType", "TurretIndex" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TurretClass_P {
    [pbr::OriginalName("AMS")] Ams = 0,
    [pbr::OriginalName("ATG")] Atg = 1,
    [pbr::OriginalName("MSL")] Msl = 2,
    [pbr::OriginalName("OTHER")] Other = 3,
  }

  #endregion

  #region Messages
  [System.Serializable]
  public sealed partial class ShipSaveFile_P : pb::IMessage<ShipSaveFile_P>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShipSaveFile_P> _parser = new pb::MessageParser<ShipSaveFile_P>(() => new ShipSaveFile_P());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ShipSaveFile_P> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocFiles.ShipDataProtocReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShipSaveFile_P() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShipSaveFile_P(ShipSaveFile_P other) : this() {
      shipChassisIndex_ = other.shipChassisIndex_;
      turretMounts_ = other.turretMounts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShipSaveFile_P Clone() {
      return new ShipSaveFile_P(this);
    }

    /// <summary>Field number for the "ShipChassis_Index" field.</summary>
    public const int ShipChassisIndexFieldNumber = 1;
    private int shipChassisIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ShipChassisIndex {
      get { return shipChassisIndex_; }
      set {
        shipChassisIndex_ = value;
      }
    }

    /// <summary>Field number for the "TurretMounts" field.</summary>
    public const int TurretMountsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ProtocFiles.TurretMount_P> _repeated_turretMounts_codec
        = pb::FieldCodec.ForMessage(18, global::ProtocFiles.TurretMount_P.Parser);
    private readonly pbc::RepeatedField<global::ProtocFiles.TurretMount_P> turretMounts_ = new pbc::RepeatedField<global::ProtocFiles.TurretMount_P>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtocFiles.TurretMount_P> TurretMounts {
      get { return turretMounts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ShipSaveFile_P);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ShipSaveFile_P other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ShipChassisIndex != other.ShipChassisIndex) return false;
      if(!turretMounts_.Equals(other.turretMounts_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ShipChassisIndex != 0) hash ^= ShipChassisIndex.GetHashCode();
      hash ^= turretMounts_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ShipChassisIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ShipChassisIndex);
      }
      turretMounts_.WriteTo(output, _repeated_turretMounts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ShipChassisIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ShipChassisIndex);
      }
      turretMounts_.WriteTo(ref output, _repeated_turretMounts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ShipChassisIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ShipChassisIndex);
      }
      size += turretMounts_.CalculateSize(_repeated_turretMounts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ShipSaveFile_P other) {
      if (other == null) {
        return;
      }
      if (other.ShipChassisIndex != 0) {
        ShipChassisIndex = other.ShipChassisIndex;
      }
      turretMounts_.Add(other.turretMounts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ShipChassisIndex = input.ReadInt32();
            break;
          }
          case 18: {
            turretMounts_.AddEntriesFrom(input, _repeated_turretMounts_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ShipChassisIndex = input.ReadInt32();
            break;
          }
          case 18: {
            turretMounts_.AddEntriesFrom(ref input, _repeated_turretMounts_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TurretMount_P : pb::IMessage<TurretMount_P>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TurretMount_P> _parser = new pb::MessageParser<TurretMount_P>(() => new TurretMount_P());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TurretMount_P> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtocFiles.ShipDataProtocReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TurretMount_P() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TurretMount_P(TurretMount_P other) : this() {
      turretType_ = other.turretType_;
      turretIndex_ = other.turretIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TurretMount_P Clone() {
      return new TurretMount_P(this);
    }

    /// <summary>Field number for the "TurretType" field.</summary>
    public const int TurretTypeFieldNumber = 1;
    private global::ProtocFiles.TurretClass_P turretType_ = global::ProtocFiles.TurretClass_P.Ams;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtocFiles.TurretClass_P TurretType {
      get { return turretType_; }
      set {
        turretType_ = value;
      }
    }

    /// <summary>Field number for the "Turret_Index" field.</summary>
    public const int TurretIndexFieldNumber = 2;
    private int turretIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TurretIndex {
      get { return turretIndex_; }
      set {
        turretIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TurretMount_P);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TurretMount_P other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TurretType != other.TurretType) return false;
      if (TurretIndex != other.TurretIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TurretType != global::ProtocFiles.TurretClass_P.Ams) hash ^= TurretType.GetHashCode();
      if (TurretIndex != 0) hash ^= TurretIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TurretType != global::ProtocFiles.TurretClass_P.Ams) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TurretType);
      }
      if (TurretIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TurretIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TurretType != global::ProtocFiles.TurretClass_P.Ams) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TurretType);
      }
      if (TurretIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TurretIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TurretType != global::ProtocFiles.TurretClass_P.Ams) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TurretType);
      }
      if (TurretIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TurretIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TurretMount_P other) {
      if (other == null) {
        return;
      }
      if (other.TurretType != global::ProtocFiles.TurretClass_P.Ams) {
        TurretType = other.TurretType;
      }
      if (other.TurretIndex != 0) {
        TurretIndex = other.TurretIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TurretType = (global::ProtocFiles.TurretClass_P) input.ReadEnum();
            break;
          }
          case 16: {
            TurretIndex = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TurretType = (global::ProtocFiles.TurretClass_P) input.ReadEnum();
            break;
          }
          case 16: {
            TurretIndex = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
